### PR TITLE
Require proper spree_backend js

### PR DESCRIPTION
**Pull request by dsawa**
When added to engine I work on as dependency, I encountered 

```
Sprockets::FileNotFound: couldn't find file 'admin/spree_backend'
  (in /home/dsawa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/spree_payu_integration-92f52a630e18/app/assets/javascripts/admin/spree_payu_integration.js:1)
```

 I believe that `admin/spree_backend` path is not present in spree since 2.2

### CODE REVIEW

**Comment by jumski** [comment]
shouldn't it be also specified in gemspec? after this change using gem with < 2.2 will fail

couldn't resist :)

**Comment by dsawa** [comment]
@jumski Cool but, it's already in gemspec :)
https://github.com/rebased/spree_payu_integration/blob/master/spree_payu_integration.gemspec#L17

**Comment by dsawa** [comment]
@jumski I wonder if this is going to be merged at all?

**Comment by jumski** [comment]
Oh lol! I thought you can merge this and it is already merged long time ago :)

Merging immediately! :p 
How are things going? Long time no see :)

**Pull request merged**
